In [2]:
import pandas as pd
import numpy as np
import keras

Using TensorFlow backend.


In [3]:
# UCI HAR Dataset
x_train = pd.read_table("UCI HAR Dataset\\train\\X_train.txt",delim_whitespace=True,header=None)

c:\users\scian\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


In [4]:
x_train

0         1         2         3         4         5         6    \
0     0.288585 -0.020294 -0.132905 -0.995279 -0.983111 -0.913526 -0.995112   
1     0.278419 -0.016411 -0.123520 -0.998245 -0.975300 -0.960322 -0.998807   
2     0.279653 -0.019467 -0.113462 -0.995380 -0.967187 -0.978944 -0.996520   
3     0.279174 -0.026201 -0.123283 -0.996091 -0.983403 -0.990675 -0.997099   
4     0.276629 -0.016570 -0.115362 -0.998139 -0.980817 -0.990482 -0.998321   
5     0.277199 -0.010098 -0.105137 -0.997335 -0.990487 -0.995420 -0.997627   
6     0.279454 -0.019641 -0.110022 -0.996921 -0.967186 -0.983118 -0.997003   
7     0.277432 -0.030488 -0.125360 -0.996559 -0.966728 -0.981585 -0.996485   
8     0.277293 -0.021751 -0.120751 -0.997328 -0.961245 -0.983672 -0.997596   
9     0.280586 -0.009960 -0.106065 -0.994803 -0.972758 -0.986244 -0.995405   
10    0.276880 -0.012722 -0.103438 -0.994815 -0.973077 -0.985357 -0.995509   
11    0.276228 -0.021441 -0.108202 -0.998246 -0.987214 -0.992727 -0.998251   
12    0.278457 -0.020415 -0.112732 -0.999135 -0.984680 -0.996274 -0.999077   
13    0.277175 -0.014713 -0.106756 -0.999188 -0.990526 -0.993365 -0.999211   
14    0.297946  0.027094 -0.061668 -0.988641 -0.816699 -0.901907 -0.988958   
15    0.279203 -0.023020 -0.122080 -0.996839 -0.974848 -0.983386 -0.997094   
16    0.279038 -0.014800 -0.116849 -0.996941 -0.981866 -0.982577 -0.997220   
17    0.280135 -0.013917 -0.106370 -0.997695 -0.987516 -0.990407 -0.998014   
18    0.277731 -0.018211 -0.109188 -0.997491 -0.993222 -0.996128 -0.997903   
19    0.275568 -0.016980 -0.111429 -0.997811 -0.990522 -0.997621 -0.998205   
20    0.277562 -0.014318 -0.107877 -0.997904 -0.994311 -0.995952 -0.998365   
21    0.277152 -0.017983 -0.106601 -0.997763 -0.989957 -0.996586 -0.998291   
22    0.275676 -0.021264 -0.110801 -0.997862 -0.990091 -0.994593 -0.998333   
23    0.279200 -0.017714 -0.109161 -0.998389 -0.987308 -0.990832 -0.998869   
24    0.281715 -0.011911 -0.102875 -0.998534 -0.988489 -0.993184 -0.998674   
25    0.278993 -0.014531 -0.106596 -0.998060 -0.986070 -0.993424 -0.998059   
26    0.275734 -0.018019 -0.106776 -0.999255 -0.993669 -0.994189 -0.999407   
27    0.144504  0.189263  0.062769 -0.904300 -0.181937 -0.443151 -0.901100   
28    0.287252 -0.037455 -0.145974 -0.982915 -0.891605 -0.941438 -0.984418   
29    0.279998 -0.019484 -0.105724 -0.992818 -0.940350 -0.981493 -0.993092   
...        ...       ...       ...       ...       ...       ...       ...   
7322  0.087902 -0.118993 -0.052787 -0.217817 -0.148752  0.079020 -0.294967   
7323  0.216468 -0.068214 -0.119832 -0.178207 -0.143102  0.094924 -0.253348   
7324  0.303490 -0.069855 -0.091222 -0.190855 -0.133971  0.134401 -0.258501   
7325  0.355975 -0.046314 -0.087425 -0.226858  0.070517  0.134833 -0.303955   
7326  0.341562 -0.006308 -0.124693 -0.226657  0.016989  0.139081 -0.311331   
7327  0.194867  0.005240 -0.148642 -0.248229 -0.109560  0.085123 -0.341040   
7328  0.193572  0.012456 -0.173717 -0.285951 -0.036560 -0.016738 -0.397237   
7329  0.354660 -0.010554 -0.196504 -0.284294 -0.046606  0.062199 -0.377721   
7330  0.389674 -0.015067 -0.166583 -0.297800 -0.120023  0.130441 -0.366625   
7331  0.306127 -0.025759 -0.103981 -0.286574 -0.117015  0.098379 -0.368546   
7332  0.188898 -0.094342 -0.062392 -0.346270 -0.235424  0.197720 -0.407151   
7333  0.215789 -0.022920 -0.236713 -0.385755 -0.189566  0.017584 -0.454614   
7334  0.407780 -0.053721 -0.160671 -0.321271 -0.089818  0.173128 -0.394279   
7335  0.260279  0.000813 -0.103406 -0.330964  0.018713  0.208689 -0.445056   
7336  0.128064 -0.027657 -0.088319 -0.280320 -0.009818  0.118190 -0.419705   
7337  0.278414 -0.070497 -0.050016 -0.228968 -0.151583  0.225156 -0.306094   
7338  0.344757 -0.045966 -0.011919 -0.272351 -0.032724  0.221100 -0.357972   
7339  0.326647  0.012036 -0.091359 -0.284641 -0.141369  0.175757 -0.367565   
7340  0.223283  0.013911 -0.214152 -0.314130 -0.287192  0.079174 -0.392787   
7341  0.363768 -0.011264 -0.27572

In [6]:
y_train = pd.read_table("UCI HAR Dataset\\train\\Y_train.txt",header=None)

c:\users\scian\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


In [7]:
y_train

0
0     5
1     5
2     5
3     5
4     5
5     5
6     5
7     5
8     5
9     5
10    5
11    5
12    5
13    5
14    5
15    5
16    5
17    5
18    5
19    5
20    5
21    5
22    5
23    5
24    5
25    5
26    5
27    4
28    4
29    4
...  ..
7322  2
7323  2
7324  2
7325  2
7326  2
7327  2
7328  2
7329  2
7330  2
7331  2
7332  2
7333  2
7334  2
7335  2
7336  2
7337  2
7338  2
7339  2
7340  2
7341  2
7342  2
7343  2
7344  2
7345  2
7346  2
7347  2
7348  2
7349  2
7350  2
7351  2

[7352 rows x 1 columns]

In [31]:
x_test = pd.read_table("UCI HAR Dataset\\test\\X_test.txt",delim_whitespace=True,header=None)
y_test = pd.read_table("UCI HAR Dataset\\test\\Y_test.txt",header=None)

c:\users\scian\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.
c:\users\scian\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


In [10]:
type(x_train)

pandas.core.frame.DataFrame

In [11]:
# convert dataframe into array
x_train = x_train.values
y_train = y_train.values
print(x_train.shape)
print(y_train.shape)

(7352, 561)
(7352, 1)


In [13]:
# One-Hot Encoding
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
y_train = ohe.fit_transform(y_train).toarray()

c:\users\scian\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [15]:
print(y_train)
print(y_train.shape)

[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
(7352, 6)


In [16]:
# Artificial Neural Network
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout  

In [29]:
model = Sequential()
model.add(Dense(48, input_dim = 561, kernel_initializer='uniform', activation='relu', ))
model.add(Dropout(0.1))
model.add(Dense(24, kernel_initializer='uniform', activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(12, kernel_initializer='uniform', activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(6, kernel_initializer='uniform', activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics = ['accuracy'])

In [30]:
# Train
model.fit(x_train, y_train, batch_size=20, epochs=10, verbose = 4)

Epoch 1/10
Epoch 2/10
Epoch 3/10
Epoch 4/10
Epoch 5/10
Epoch 6/10
Epoch 7/10
Epoch 8/10
Epoch 9/10
Epoch 10/10


In [32]:
# Training and Testing Accuracy
train_acc = model.evaluate(x_train, y_train)
print("Training Accuracy:", train_acc[1])
y_test = ohe.fit_transform(y_test).toarray()
test_acc = model.evaluate(x_test, y_test)
print("Testing Accuracy:", test_acc[1])

7352/7352 [==============================] - 0s 64us/step
Training Accuracy: 0.9748367791077258
2947/2947 [==============================] - 0s 43us/step
Testing Accuracy: 0.9358669833729216


c:\users\scian\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
